<?php

declare(strict_types=1);

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group([
        'key' => 'group_59ede2f88a7b5',
        'title' => __('Timeline', 'modularity-timeline'),
        'fields' => [
            0 => [
                'key' => 'field_68307ff367393',
                'label' => __('Sequential mode', 'modularity-timeline'),
                'name' => 'timeline_sequential_mode',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('If enabled timeline events won\'t have an explicit date or time but rather be steps that are part of a sequential process.', 'modularity-timeline'),
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            1 => [
                'key' => 'field_5d5416b7f92ed',
                'label' => __('Format', 'modularity-timeline'),
                'name' => 'timeline_format',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => __('Show time instead of date', 'modularity-timeline'),
                'required' => 0,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_68307ff367393',
                            'operator' => '!=',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ],
            2 => [
                'key' => 'field_59ede644f0d68',
                'label' => __('Date format', 'modularity-timeline'),
                'name' => 'timeline_date_format',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_5d5416b7f92ed',
                            'operator' => '!=',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_68307ff367393',
                            'operator' => '!=',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'dmy' => __('Day Month Year', 'modularity-timeline'),
                    'dm' => __('Day Month', 'modularity-timeline'),
                    'y' => __('Year', 'modularity-timeline'),
                ],
                'default_value' => __('dmy:Day-Month-Year', 'modularity-timeline'),
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ],
            3 => [
                'key' => 'field_5d5417466c393',
                'label' => __('Timestamp format', 'modularity-timeline'),
                'name' => 'timeline_timestamp_format',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => [
                    0 => [
                        0 => [
                            'field' => 'field_5d5416b7f92ed',
                            'operator' => '==',
                            'value' => '1',
                        ],
                        1 => [
                            'field' => 'field_68307ff367393',
                            'operator' => '!=',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'Hi' => __('Hour minutes', 'modularity-timeline'),
                ],
                'default_value' => __('Hi:Hour-minutes', 'modularity-timeline'),
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ],
            4 => [
                'key' => 'field_59ede30ef0d63',
                'label' => __('Tidslinjehändelser', 'modularity-timeline'),
                'name' => 'timeline_events',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'block',
                'button_label' => __('Add Row', 'modularity-timeline'),
                'rows_per_page' => 20,
                'acfe_repeater_stylised_button' => 0,
                'sub_fields' => [
                    0 => [
                        'key' => 'field_59ede46ef0d64',
                        'label' => __('Title', 'modularity-timeline'),
                        'name' => 'title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    1 => [
                        'key' => 'field_59ede485f0d65',
                        'label' => __('Content', 'modularity-timeline'),
                        'name' => 'content',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => 4,
                        'new_lines' => 'wpautop',
                        'acfe_textarea_code' => 0,
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    2 => [
                        'key' => 'field_5a44b698607e2',
                        'label' => __('Link', 'modularity-timeline'),
                        'name' => 'link',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => __('Add a link to this event', 'modularity-timeline'),
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    3 => [
                        'key' => 'field_59ede49df0d66',
                        'label' => __('Date', 'modularity-timeline'),
                        'name' => 'date',
                        'aria-label' => '',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_5d5416b7f92ed',
                                    'operator' => '!=',
                                    'value' => '1',
                                ],
                                1 => [
                                    'field' => 'field_68307ff367393',
                                    'operator' => '!=',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'display_format' => 'Y-m-d',
                        'return_format' => 'Y-m-d',
                        'first_day' => 1,
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    4 => [
                        'key' => 'field_5d5414c0677aa',
                        'label' => __('Timestamp', 'modularity-timeline'),
                        'name' => 'timestamp',
                        'aria-label' => '',
                        'type' => 'time_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_5d5416b7f92ed',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                                1 => [
                                    'field' => 'field_68307ff367393',
                                    'operator' => '!=',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'display_format' => 'H:i:s',
                        'return_format' => 'H:i:s',
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    5 => [
                        'key' => 'field_59ede561f0d67',
                        'label' => __('Image', 'modularity-timeline'),
                        'name' => 'image',
                        'aria-label' => '',
                        'type' => 'file',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => [
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ],
                        'return_format' => 'array',
                        'library' => 'all',
                        'min_size' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'uploader' => '',
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                    6 => [
                        'key' => 'field_683080e2961cd',
                        'label' => __('Active step', 'modularity-timeline'),
                        'name' => 'active_step',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => __('Highlight this event as being the current one', 'modularity-timeline'),
                        'required' => 0,
                        'conditional_logic' => [
                            0 => [
                                0 => [
                                    'field' => 'field_68307ff367393',
                                    'operator' => '==',
                                    'value' => '1',
                                ],
                            ],
                        ],
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                        'message' => '',
                        'default_value' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'ui' => 1,
                        'parent_repeater' => 'field_59ede30ef0d63',
                    ],
                ],
            ],
        ],
        'location' => [
            0 => [
                0 => [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mod-timeline',
                ],
            ],
            1 => [
                0 => [
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/timeline',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ]);
}
